module.exports = {
  MONGODB_URI: process.env.MONGODB_URI,
  SESSION_SECRET: process.env.SESSION_SECRET,
  GMAIL_CLIENT_ID:process.env.GMAIL_CLIENT_ID,
  GMAIL_CLIENT_SECRET:process.env.GMAIL_CLIENT_SECRET,
  GMAIL_REDIRECT_URI:process.env.GMAIL_REDIRECT_URI,
  GMAIL_REFRESH_TOKEN:process.env.GMAIL_REFRESH_TOKEN,
  EMAIL_FROM:process.env.EMAIL_FROM,
  BASE_URL:process.env.BASE_URL,
}